# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Correct and Incorrect
email: roseman.tom@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  News topic in which I have an opinion that may or may not be correct.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: roseman_tom
github_username:  tfroseman

#SEO Info
twitter:
  username: roseman_tom



# Build settings
markdown: kramdown

gems: [jekyll-seo-tag]
